create database practice_problem3

CREATE TABLE customers (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    email VARCHAR(50)
)
CREATE TABLE orders (
    id INT PRIMARY KEY,
    customer_id INT,
    order_date DATE,
    FOREIGN KEY (customer_id) REFERENCES customers(id)
)

CREATE TABLE products (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    price DECIMAL(10, 2)
)

CREATE TABLE order_items (
    id INT PRIMARY KEY,
    order_id INT,
    product_id INT,
    quantity INT,
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
)

CREATE TABLE suppliers (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    address VARCHAR(100),
    phone VARCHAR(20)
)

--Which customers have placed orders on a certain date?
--What is the total amount spent by each customer on all of their orders?
--Which products have been ordered by each customer, and how many of each product have they ordered?
--Which customers have not placed any orders yet?
--Which suppliers have provided products that have been ordered by customers?
--What is the total revenue generated by each supplier's products?
--Which products have not been ordered yet?
--Which customers have ordered the most products in a given time period?
--Which customers have ordered products from multiple suppliers?
--What is the average price of the products ordered by each customer?


